//
//  AllahovoIme.swift
//  MuslimApp
//
//  Created by Muhedin Alic on 03.06.24.
//

import Foundation

struct AllahovoIme: Identifiable {
    let id = UUID()
    let redniBroj: Int
    let ime: String
    let imeNaArapskom: String
    let prevodImena: String
}

let imena: [AllahovoIme] = [
    AllahovoIme(redniBroj: 1, ime: "Allah", imeNaArapskom: "الله", prevodImena: "Jedan Jedini Bog"),
    AllahovoIme(redniBroj: 2, ime: "Er-Rahman", imeNaArapskom: "الرّحمان", prevodImena: "Blagi, Premilosrdni"),
    AllahovoIme(redniBroj: 3, ime: "Er-Rahim", imeNaArapskom: "الرّحيم", prevodImena: "Svemilostivi"),
    AllahovoIme(redniBroj: 4, ime: "El-Melik", imeNaArapskom: "المَلِك", prevodImena: "Vladar, Suvereni"),
    AllahovoIme(redniBroj: 5, ime: "El-Kuddus", imeNaArapskom: "القُدّوس", prevodImena: "Sveti, Najčistiji"),
    AllahovoIme(redniBroj: 6, ime: "Es-Selam", imeNaArapskom: "السّلام", prevodImena: "Onaj koji je bez mane"),
    AllahovoIme(redniBroj: 7, ime: "El-Mu’min", imeNaArapskom: "المؤمن", prevodImena: "Pouzdani, Onaj koji daje mir"),
    AllahovoIme(redniBroj: 8, ime: "El-Muhejmin", imeNaArapskom: "المهيمن", prevodImena: "Zaštitnik, Onaj koji daje sigurnost"),
    AllahovoIme(redniBroj: 9, ime: "El-Aziz", imeNaArapskom: "العزيز", prevodImena: "Onaj koji sve pazi i prati"),
    AllahovoIme(redniBroj: 10, ime: "El-Džebbar", imeNaArapskom: "الجبّار", prevodImena: "Silni"),
    AllahovoIme(redniBroj: 11, ime: "El-Mutekebbir", imeNaArapskom: "المتكبر", prevodImena: "Gordi"),
    AllahovoIme(redniBroj: 12, ime: "El-Halik", imeNaArapskom: "الخالق", prevodImena: "Stvoritelj, Odlučujući, Onaj koji daje mjeru svakoj stvari"),
    AllahovoIme(redniBroj: 13, ime: "El-Bari’", imeNaArapskom: "البارئ", prevodImena: "Onaj koji divno stvara"),
    AllahovoIme(redniBroj: 14, ime: "El-Musavvir", imeNaArapskom: "المصور", prevodImena: "Oblikovatelj"),
    AllahovoIme(redniBroj: 15, ime: "El-Gaffar", imeNaArapskom: "الغفار", prevodImena: "Svepraštajući"),
    AllahovoIme(redniBroj: 16, ime: "El-Kahhar", imeNaArapskom: "القهار", prevodImena: "Onaj koji sve nadvladava"),
    AllahovoIme(redniBroj: 17, ime: "El-Vehhab", imeNaArapskom: "الوهاب", prevodImena: "Milostivi darivatelj, Onaj koji obilno dariva"),
    AllahovoIme(redniBroj: 18, ime: "Er-Rezzak", imeNaArapskom: "الرزاق", prevodImena: "Onaj koji obilnu opskrbu daje"),
    AllahovoIme(redniBroj: 19, ime: "El-Fettah", imeNaArapskom: "الفتاح", prevodImena: "Onaj koji sve rješava i otklanja prepreke"),
    AllahovoIme(redniBroj: 20, ime: "El-Alim", imeNaArapskom: "العليم", prevodImena: "Sveznajući"),
    AllahovoIme(redniBroj: 21, ime: "El-Kabid", imeNaArapskom: "القابض", prevodImena: "Onaj koji steže i stišće"),
    AllahovoIme(redniBroj: 22, ime: "El-Basit", imeNaArapskom: "الباسط", prevodImena: "Onaj koji pruža i otpušta"),
    AllahovoIme(redniBroj: 23, ime: "El-Hafid", imeNaArapskom: "الخافض", prevodImena: "Onaj koji spušta"),
    AllahovoIme(redniBroj: 24, ime: "Er-Rafi’", imeNaArapskom: "الرافع", prevodImena: "Onaj koji uzdiže"),
    AllahovoIme(redniBroj: 25, ime: "El-Mu’izz", imeNaArapskom: "المعز", prevodImena: "Onaj koji uzvisuje, daje čast i slavu"),
    AllahovoIme(redniBroj: 26, ime: "El-Muzill", imeNaArapskom: "المذل", prevodImena: "Onaj koji ponižava, daje poniženje"),
    AllahovoIme(redniBroj: 27, ime: "Es-Semi’", imeNaArapskom: "السميع", prevodImena: "Svečujni"),
    AllahovoIme(redniBroj: 28, ime: "El-Besir", imeNaArapskom: "البصير", prevodImena: "Svevideći"),
    AllahovoIme(redniBroj: 29, ime: "El-Hakem", imeNaArapskom: "الحكم", prevodImena: "Sudac, Onaj koji postavlja svoja pravila, donosi svoj sud i izriče presudu"),
    AllahovoIme(redniBroj: 30, ime: "El-‘Adl", imeNaArapskom: "العدل", prevodImena: "Pravedni"),
    AllahovoIme(redniBroj: 31, ime: "El-Latif", imeNaArapskom: "اللطيف", prevodImena: "Dobrostivi, Dobri"),
    AllahovoIme(redniBroj: 32, ime: "El-Habir", imeNaArapskom: "الخبير", prevodImena: "O svemu obaviješteni"),
    AllahovoIme(redniBroj: 33, ime: "El-Halim", imeNaArapskom: "الحليم", prevodImena: "Blagi, Srdačni"),
    AllahovoIme(redniBroj: 34, ime: "El-Azim", imeNaArapskom: "العظيم", prevodImena: "Veliki, Neizmjerljivi"),
    AllahovoIme(redniBroj: 35, ime: "El-Gafur", imeNaArapskom: "الغفور", prevodImena: "Svepraštajući"),
    AllahovoIme(redniBroj: 36, ime: "Eš-Šekur", imeNaArapskom: "الشكور", prevodImena: "Zahvalni, Onaj koji uzvraća nagradom za vjernost"),
    AllahovoIme(redniBroj: 37, ime: "El-‘Alijj", imeNaArapskom: "العلي", prevodImena: "Uzvišeni"),
    AllahovoIme(redniBroj: 38, ime: "El-Kebir", imeNaArapskom: "الكبير", prevodImena: "Beskrajno veliki, Najizdignutiji"),
    AllahovoIme(redniBroj: 39, ime: "El-Hafiz", imeNaArapskom: "الحفيظ", prevodImena: "Onaj koji čuva"),
    AllahovoIme(redniBroj: 40, ime: "El-Mukit", imeNaArapskom: "المقيت", prevodImena: "Onaj koji pazi i uzdržava"),
    AllahovoIme(redniBroj: 41, ime: "El-Hasib", imeNaArapskom: "الحسيب", prevodImena: "Onaj koji obračun svodi"),
    AllahovoIme(redniBroj: 42, ime: "El-Dželil", imeNaArapskom: "الجليل", prevodImena: "Veličanstveni"),
    AllahovoIme(redniBroj: 43, ime: "El-Kerim", imeNaArapskom: "الكريم", prevodImena: "Plemeniti, Najdarežljiviji"),
    AllahovoIme(redniBroj: 44, ime: "Er-Rakib", imeNaArapskom: "الرقيب", prevodImena: "Onaj koji stalno bdi"),
    AllahovoIme(redniBroj: 45, ime: "El-Mudžib", imeNaArapskom: "المجيب", prevodImena: "Onaj koji molbe prima"),
    AllahovoIme(redniBroj: 46, ime: "El-Vasi’", imeNaArapskom: "الواسع", prevodImena: "Sveobuhvatni"),
    AllahovoIme(redniBroj: 47, ime: "El-Hakim", imeNaArapskom: "الحكيم", prevodImena: "Mudri, Sveznajući"),
    AllahovoIme(redniBroj: 48, ime: "El-Vedud", imeNaArapskom: "الودود", prevodImena: "Dobrostivi, Blagonakloni"),
    AllahovoIme(redniBroj: 49, ime: "El-Medžid", imeNaArapskom: "المجيد", prevodImena: "Slavni, Hvaljeni"),
    AllahovoIme(redniBroj: 50, ime: "El-Ba’ith", imeNaArapskom: "الباعث", prevodImena: "Onaj koji oživljava"),
    AllahovoIme(redniBroj: 51, ime: "Eš-Šehid", imeNaArapskom: "الشهيد", prevodImena: "Svjedok, Svjedočanstvo"),
    AllahovoIme(redniBroj: 52, ime: "El-Hakk", imeNaArapskom: "الحق", prevodImena: "Istina, Pravedni"),
    AllahovoIme(redniBroj: 53, ime: "El-Vekil", imeNaArapskom: "الوكيل", prevodImena: "Zaštitnik, Pomagač"),
    AllahovoIme(redniBroj: 54, ime: "El-Kavijj", imeNaArapskom: "القوى", prevodImena: "Jaki"),
    AllahovoIme(redniBroj: 55, ime: "El-Metin", imeNaArapskom: "المتين", prevodImena: "Moćni, Jaki"),
    AllahovoIme(redniBroj: 56, ime: "El-Velijj", imeNaArapskom: "الولى", prevodImena: "Zaštitnik"),
    AllahovoIme(redniBroj: 57, ime: "El-Hamid", imeNaArapskom: "الحميد", prevodImena: "Hvaljeni"),
    AllahovoIme(redniBroj: 58, ime: "El-Muhsi", imeNaArapskom: "المحصى", prevodImena: "Onaj koji sve računa"),
    AllahovoIme(redniBroj: 59, ime: "El-Mubdi’", imeNaArapskom: "المبدئ", prevodImena: "Onaj koji iz ničega stvara"),
    AllahovoIme(redniBroj: 60, ime: "El-Mu’id", imeNaArapskom: "المعيد", prevodImena: "Onaj koji vraća u život"),
    AllahovoIme(redniBroj: 61, ime: "El-Muhji", imeNaArapskom: "المحيى", prevodImena: "Onaj koji oživljava"),
    AllahovoIme(redniBroj: 62, ime: "El-Mumit", imeNaArapskom: "المميت", prevodImena: "Onaj koji usmrćuje"),
    AllahovoIme(redniBroj: 63, ime: "El-Hajj", imeNaArapskom: "الحي", prevodImena: "Živi, Besmrtni"),
    AllahovoIme(redniBroj: 64, ime: "El-Kajum", imeNaArapskom: "القيوم", prevodImena: "Vječni, Stalni"),
    AllahovoIme(redniBroj: 65, ime: "El-Vadžid", imeNaArapskom: "الواجد", prevodImena: "Bogati, Neovisni"),
    AllahovoIme(redniBroj: 66, ime: "El-Madžid", imeNaArapskom: "الماجد", prevodImena: "Plemeniti, Najdarežljiviji"),
    AllahovoIme(redniBroj: 67, ime: "El-Vahid", imeNaArapskom: "الواحد", prevodImena: "Jedini, Jedinstveni"),
    AllahovoIme(redniBroj: 68, ime: "Es-Samed", imeNaArapskom: "الصمد", prevodImena: "Gospodar, Utočište svakog stvorenja"),
    AllahovoIme(redniBroj: 69, ime: "El-Kadir", imeNaArapskom: "القادر", prevodImena: "Svemoćni"),
    AllahovoIme(redniBroj: 70, ime: "El-Muktadir", imeNaArapskom: "المقتدر", prevodImena: "Onaj koji sve nadvladava"),
    AllahovoIme(redniBroj: 71, ime: "El-Mukaddim", imeNaArapskom: "المقدم", prevodImena: "Onaj koji daje prednost, uzvisuje"),
    AllahovoIme(redniBroj: 72, ime: "El-Muahhir", imeNaArapskom: "المؤخر", prevodImena: "Onaj koji ponižava"),
    AllahovoIme(redniBroj: 73, ime: "El-Evvel", imeNaArapskom: "الأول", prevodImena: "Prvi"),
    AllahovoIme(redniBroj: 74, ime: "El-Ahir", imeNaArapskom: "الأخر", prevodImena: "Posljednji"),
    AllahovoIme(redniBroj: 75, ime: "Ez-Zahir", imeNaArapskom: "الظاهر", prevodImena: "Vidljivi, Onaj koji je očit"),
    AllahovoIme(redniBroj: 76, ime: "El-Batin", imeNaArapskom: "الباطن", prevodImena: "Nevidljivi, Prikriveni"),
    AllahovoIme(redniBroj: 77, ime: "El-Vali", imeNaArapskom: "الوالي", prevodImena: "Zaštitnik svih stvorenja"),
    AllahovoIme(redniBroj: 78, ime: "El-Mute’ali", imeNaArapskom: "المتعالي", prevodImena: "Najuzvišeniji"),
    AllahovoIme(redniBroj: 79, ime: "El-Berr", imeNaArapskom: "البر", prevodImena: "Dobročinitelj"),
    AllahovoIme(redniBroj: 80, ime: "Et-Tevvab", imeNaArapskom: "التواب", prevodImena: "Onaj koji prima pokajanje"),
    AllahovoIme(redniBroj: 81, ime: "El-Muntekim", imeNaArapskom: "المنتقم", prevodImena: "Onaj koji s pravom kažnjava"),
    AllahovoIme(redniBroj: 82, ime: "El-Afuvv", imeNaArapskom: "العفو", prevodImena: "Onaj koji prašta"),
    AllahovoIme(redniBroj: 83, ime: "Er-Ra’uf", imeNaArapskom: "الرؤوف", prevodImena: "Blagi, Milostivi"),
    AllahovoIme(redniBroj: 84, ime: "Malik-ul-Mulk", imeNaArapskom: "مالك الملك", prevodImena: "Vladar, Suvereni"),
    AllahovoIme(redniBroj: 85, ime: "Zu-l-Dželal-i ve-l-Ikram", imeNaArapskom: "ذو الجلال و الإكرام", prevodImena: "Posjednik veličine i plemenitosti"),
    AllahovoIme(redniBroj: 86, ime: "El-Muksit", imeNaArapskom: "المقسط", prevodImena: "Pravedni"),
    AllahovoIme(redniBroj: 87, ime: "El-Džami’", imeNaArapskom: "الجامع", prevodImena: "Onaj koji spaja"),
    AllahovoIme(redniBroj: 88, ime: "El-Ganiyy", imeNaArapskom: "الغنى", prevodImena: "Bogati, Neovisni"),
    AllahovoIme(redniBroj: 89, ime: "El-Mugni", imeNaArapskom: "المغنى", prevodImena: "Onaj koji obilje daje"),
    AllahovoIme(redniBroj: 90, ime: "El-Mani’", imeNaArapskom: "المانع", prevodImena: "Onaj koji sprečava"),
    AllahovoIme(redniBroj: 91, ime: "Ed-Darr", imeNaArapskom: "الضآر", prevodImena: "Onaj koji može nauditi"),
    AllahovoIme(redniBroj: 92, ime: "En-Nafi’", imeNaArapskom: "النافع", prevodImena: "Onaj koji koristi"),
    AllahovoIme(redniBroj: 93, ime: "En-Nur", imeNaArapskom: "النور", prevodImena: "Svjetlo"),
    AllahovoIme(redniBroj: 94, ime: "El-Hadi", imeNaArapskom: "الهادى", prevodImena: "Onaj koji upućuje"),
    AllahovoIme(redniBroj: 95, ime: "El-Bedi’", imeNaArapskom: "البديع", prevodImena: "Onaj koji stvara izvore"),
    AllahovoIme(redniBroj: 96, ime: "El-Baki", imeNaArapskom: "الباقى", prevodImena: "Vječni"),
    AllahovoIme(redniBroj: 97, ime: "El-Varis", imeNaArapskom: "الوارث", prevodImena: "Nasljednik svega"),
    AllahovoIme(redniBroj: 98, ime: "Er-Rešid", imeNaArapskom: "الرشيد", prevodImena: "Onaj koji ispravno vodi"),
    AllahovoIme(redniBroj: 99, ime: "Es-Sabur", imeNaArapskom: "الصبور", prevodImena: "Strpljivi")
]

