//
//  Sura.swift
//  MuslimApp
//
//  Created by Muhedin Alic on 01.06.24.
//

import Foundation

struct Sura: Identifiable {
    let id = UUID()
    let redniBroj: Int
    let sura: String
    let imeSureNaArapskom: String
    let prevodImenaSure: String
    let tipSure: String // Oznaka medinska ili mekanska
    let brojAjeta: Int
}


let sure: [Sura] = [
    Sura(redniBroj: 1, sura: "El-Fatiha", imeSureNaArapskom: "الفاتحة", prevodImenaSure: "Pristup", tipSure: "mekanska", brojAjeta: 7),
    Sura(redniBroj: 2, sura: "El-Bekare", imeSureNaArapskom: "البقرة", prevodImenaSure: "Krava", tipSure: "medinska", brojAjeta: 286),
    Sura(redniBroj: 3, sura: "Ali-Imran", imeSureNaArapskom: "آل عمران", prevodImenaSure: "Imranova porodica", tipSure: "medinska", brojAjeta: 200),
    Sura(redniBroj: 4, sura: "En-Nisa", imeSureNaArapskom: "النساء", prevodImenaSure: "Žene", tipSure: "medinska", brojAjeta: 176),
    Sura(redniBroj: 5, sura: "El-Maide", imeSureNaArapskom: "المائدة", prevodImenaSure: "Trpeza", tipSure: "medinska", brojAjeta: 120),
    Sura(redniBroj: 6, sura: "El-En'am", imeSureNaArapskom: "الأنعام", prevodImenaSure: "Stoka", tipSure: "mekkanska", brojAjeta: 165),
    Sura(redniBroj: 7, sura: "El-E'raf", imeSureNaArapskom: "الأعراف", prevodImenaSure: "Visine", tipSure: "mekkanska", brojAjeta: 206),
    Sura(redniBroj: 8, sura: "El-Enfal", imeSureNaArapskom: "الأنفال", prevodImenaSure: "Ratni plijen", tipSure: "medinska", brojAjeta: 75),
    Sura(redniBroj: 9, sura: "Et-Tevbe", imeSureNaArapskom: "التوبة", prevodImenaSure: "Pokajanje", tipSure: "medinska", brojAjeta: 129),
    Sura(redniBroj: 10, sura: "Junus", imeSureNaArapskom: "يونس", prevodImenaSure: "Junus", tipSure: "mekkanska", brojAjeta: 109),
    Sura(redniBroj: 11, sura: "Hud", imeSureNaArapskom: "هود", prevodImenaSure: "Hud", tipSure: "mekkanska", brojAjeta: 123),
    Sura(redniBroj: 12, sura: "Jusuf", imeSureNaArapskom: "يوسف", prevodImenaSure: "Jusuf", tipSure: "mekanska", brojAjeta: 111),
    Sura(redniBroj: 13, sura: "Er-Ra'd", imeSureNaArapskom: "الرعد", prevodImenaSure: "Grom", tipSure: "mekanska", brojAjeta: 43),
    Sura(redniBroj: 14, sura: "Ibrahim", imeSureNaArapskom: "إبراهيم", prevodImenaSure: "Ibrahim", tipSure: "mekanska", brojAjeta: 52),
    Sura(redniBroj: 15, sura: "El-Hidžr", imeSureNaArapskom: "الحجر", prevodImenaSure: "Kamen", tipSure: "mekanska", brojAjeta: 99),
    Sura(redniBroj: 16, sura: "En-Nahl", imeSureNaArapskom: "النحل", prevodImenaSure: "Pčele", tipSure: "mekanska", brojAjeta: 128),
    Sura(redniBroj: 17, sura: "El-Isra", imeSureNaArapskom: "الإسراء", prevodImenaSure: "Noćno putovanje", tipSure: "mekanska", brojAjeta: 111),
    Sura(redniBroj: 18, sura: "El-Kehf", imeSureNaArapskom: "الكهف", prevodImenaSure: "Pećina", tipSure: "mekanska", brojAjeta: 110),
    Sura(redniBroj: 19, sura: "Merjem", imeSureNaArapskom: "مريم", prevodImenaSure: "Merjem", tipSure: "mekanska", brojAjeta: 98),
    Sura(redniBroj: 20, sura: "Ta-Ha", imeSureNaArapskom: "طه", prevodImenaSure: "Ta-Ha", tipSure: "mekanska", brojAjeta: 135),
    Sura(redniBroj: 21, sura: "El-Enbiya", imeSureNaArapskom: "الأنبياء", prevodImenaSure: "Proroci", tipSure: "mekanska", brojAjeta: 112),
    Sura(redniBroj: 22, sura: "El-Hadždž", imeSureNaArapskom: "الحج", prevodImenaSure: "Hadždž", tipSure: "mekanska", brojAjeta: 78),
    Sura(redniBroj: 23, sura: "El-Mu'minun", imeSureNaArapskom: "المؤمنون", prevodImenaSure: "Vjernici", tipSure: "mekanska", brojAjeta: 118),
    Sura(redniBroj: 24, sura: "En-Nur", imeSureNaArapskom: "النور", prevodImenaSure: "Svjetlost", tipSure: "medinska", brojAjeta: 64),
    Sura(redniBroj: 25, sura: "El-Furqan", imeSureNaArapskom: "الفرقان", prevodImenaSure: "Razlikovanje", tipSure: "mekanska", brojAjeta: 77),
    Sura(redniBroj: 26, sura: "Eš-Šu'ara", imeSureNaArapskom: "الشعراء", prevodImenaSure: "Pjesnici", tipSure: "mekanska", brojAjeta: 227),
    Sura(redniBroj: 27, sura: "En-Neml", imeSureNaArapskom: "النمل", prevodImenaSure: "Mravi", tipSure: "mekanska", brojAjeta: 93),
    Sura(redniBroj: 28, sura: "El-Kasas", imeSureNaArapskom: "القصص", prevodImenaSure: "Pripovijesti", tipSure: "mekanska", brojAjeta: 88),
    Sura(redniBroj: 29, sura: "El-Ankebut", imeSureNaArapskom: "العنكبوت", prevodImenaSure: "Pauk", tipSure: "mekanska", brojAjeta: 69),
    Sura(redniBroj: 30, sura: "El-Rum", imeSureNaArapskom: "الروم", prevodImenaSure: "Rimljani", tipSure: "mekanska", brojAjeta: 60),
    Sura(redniBroj: 31, sura: "Lukman", imeSureNaArapskom: "لقمان", prevodImenaSure: "Lukman", tipSure: "mekanska", brojAjeta: 34),
    Sura(redniBroj: 32, sura: "Es-Secde", imeSureNaArapskom: "السجدة", prevodImenaSure: "Poklon", tipSure: "mekanska", brojAjeta: 30),
    Sura(redniBroj: 33, sura: "El-Ahzab", imeSureNaArapskom: "الأحزاب", prevodImenaSure: "Savezne vojske", tipSure: "medinska", brojAjeta: 73),
    Sura(redniBroj: 34, sura: "Sebe", imeSureNaArapskom: "سبأ", prevodImenaSure: "Sebe", tipSure: "mekanska", brojAjeta: 54),
    Sura(redniBroj: 35, sura: "Fatir", imeSureNaArapskom: "فاطر", prevodImenaSure: "Stvoritelj", tipSure: "mekanska", brojAjeta: 45),
    Sura(redniBroj: 36, sura: "Jasin", imeSureNaArapskom: "يس", prevodImenaSure: "Jasin", tipSure: "mekanska", brojAjeta: 83),
    Sura(redniBroj: 37, sura: "Es-Saffat", imeSureNaArapskom: "الصافات", prevodImenaSure: "Postrojeni", tipSure: "mekanska", brojAjeta: 182),
    Sura(redniBroj: 38, sura: "Sad", imeSureNaArapskom: "ص", prevodImenaSure: "Sad", tipSure: "mekanska", brojAjeta: 88),
    Sura(redniBroj: 39, sura: "Ez-Zumer", imeSureNaArapskom: "الزمر", prevodImenaSure: "Skupovi", tipSure: "mekanska", brojAjeta: 75),
    Sura(redniBroj: 40, sura: "Gafir", imeSureNaArapskom: "غافر", prevodImenaSure: "Oprostitelj", tipSure: "mekanska", brojAjeta: 85),
    Sura(redniBroj: 41, sura: "Fussilet", imeSureNaArapskom: "فصلت", prevodImenaSure: "Objašnjene", tipSure: "mekanska", brojAjeta: 54),
    Sura(redniBroj: 42, sura: "Eš-Šura", imeSureNaArapskom: "الشورى", prevodImenaSure: "Vijećanje", tipSure: "mekanska", brojAjeta: 53),
    Sura(redniBroj: 43, sura: "Ez-Zuhruf", imeSureNaArapskom: "الزخرف", prevodImenaSure: "Ukras", tipSure: "mekanska", brojAjeta: 89),
    Sura(redniBroj: 44, sura: "Ed-Duhan", imeSureNaArapskom: "الدخان", prevodImenaSure: "Dim", tipSure: "mekanska", brojAjeta: 59),
    Sura(redniBroj: 45, sura: "El-Džasija", imeSureNaArapskom: "الجاثية", prevodImenaSure: "Klečeći", tipSure: "mekanska", brojAjeta: 37),
    Sura(redniBroj: 46, sura: "El-Ahkaf", imeSureNaArapskom: "الأحقاف", prevodImenaSure: "Pješčana brda", tipSure: "mekanska", brojAjeta: 35),
    Sura(redniBroj: 47, sura: "Muhammed", imeSureNaArapskom: "محمد", prevodImenaSure: "Muhammed", tipSure: "medinska", brojAjeta: 38),
    Sura(redniBroj: 48, sura: "El-Feth", imeSureNaArapskom: "الفتح", prevodImenaSure: "Pobjeda", tipSure: "medinska", brojAjeta: 29),
    Sura(redniBroj: 49, sura: "El-Hudžurat", imeSureNaArapskom: "الحجرات", prevodImenaSure: "Sobe", tipSure: "medinska", brojAjeta: 18),
    Sura(redniBroj: 50, sura: "Kaf", imeSureNaArapskom: "ق", prevodImenaSure: "Kaf", tipSure: "mekanska", brojAjeta: 45),
    Sura(redniBroj: 51, sura: "Ez-Zarijat", imeSureNaArapskom: "الذاريات", prevodImenaSure: "Vjetrovi", tipSure: "mekanska", brojAjeta: 60),
    Sura(redniBroj: 52, sura: "Et-Tur", imeSureNaArapskom: "الطور", prevodImenaSure: "Planina", tipSure: "mekanska", brojAjeta: 49),
    Sura(redniBroj: 53, sura: "En-Nedžm", imeSureNaArapskom: "النجم", prevodImenaSure: "Zvijezda", tipSure: "mekanska", brojAjeta: 62),
    Sura(redniBroj: 54, sura: "El-Kamer", imeSureNaArapskom: "القمر", prevodImenaSure: "Mjesec", tipSure: "mekanska", brojAjeta: 55),
    Sura(redniBroj: 55, sura: "Er-Rahman", imeSureNaArapskom: "الرحمن", prevodImenaSure: "Milostivi", tipSure: "medinska", brojAjeta: 78),
    Sura(redniBroj: 56, sura: "El-Vakia", imeSureNaArapskom: "الواقعة", prevodImenaSure: "Događaj", tipSure: "mekanska", brojAjeta: 96),
    Sura(redniBroj: 57, sura: "El-Hadid", imeSureNaArapskom: "الحديد", prevodImenaSure: "Željezo", tipSure: "medinska", brojAjeta: 29),
    Sura(redniBroj: 58, sura: "El-Mudžadila", imeSureNaArapskom: "المجادلة", prevodImenaSure: "Rasprava", tipSure: "medinska", brojAjeta: 22),
    Sura(redniBroj: 59, sura: "El-Hašr", imeSureNaArapskom: "الحشر", prevodImenaSure: "Progonstvo", tipSure: "medinska", brojAjeta: 24),
    Sura(redniBroj: 60, sura: "El-Mumtehine", imeSureNaArapskom: "الممتحنة", prevodImenaSure: "Žena koja se ispituje", tipSure: "medinska", brojAjeta: 13),
    Sura(redniBroj: 61, sura: "Es-Saff", imeSureNaArapskom: "الصف", prevodImenaSure: "Borbeni redovi", tipSure: "medinska", brojAjeta: 14),
    Sura(redniBroj: 62, sura: "El-Džuma", imeSureNaArapskom: "الجمعة", prevodImenaSure: "Petak", tipSure: "medinska", brojAjeta: 11),
    Sura(redniBroj: 63, sura: "El-Munafikun", imeSureNaArapskom: "المنافقون", prevodImenaSure: "Licemjeri", tipSure: "medinska", brojAjeta: 11),
    Sura(redniBroj: 64, sura: "Et-Tegabun", imeSureNaArapskom: "التغابن", prevodImenaSure: "Gubitak i dobitak", tipSure: "medinska", brojAjeta: 18),
    Sura(redniBroj: 65, sura: "Et-Talak", imeSureNaArapskom: "الطلاق", prevodImenaSure: "Razvod", tipSure: "medinska", brojAjeta: 12),
    Sura(redniBroj: 66, sura: "Et-Tahrim", imeSureNaArapskom: "التحريم", prevodImenaSure: "Zabrana", tipSure: "medinska", brojAjeta: 12),
    Sura(redniBroj: 67, sura: "El-Mulk", imeSureNaArapskom: "الملك", prevodImenaSure: "Vlast", tipSure: "mekanska", brojAjeta: 30),
    Sura(redniBroj: 68, sura: "El-Kalem", imeSureNaArapskom: "القلم", prevodImenaSure: "Pero", tipSure: "mekanska", brojAjeta: 52),
    Sura(redniBroj: 69, sura: "El-Hakka", imeSureNaArapskom: "الحاقة", prevodImenaSure: "Neizbježna kazna", tipSure: "mekanska", brojAjeta: 52),
    Sura(redniBroj: 70, sura: "El-Me'aridž", imeSureNaArapskom: "المعارج", prevodImenaSure: "Stube", tipSure: "mekanska", brojAjeta: 44),
    Sura(redniBroj: 71, sura: "Nuh", imeSureNaArapskom: "نوح", prevodImenaSure: "Nuh", tipSure: "mekanska", brojAjeta: 28),
    Sura(redniBroj: 72, sura: "El-Džinn", imeSureNaArapskom: "الجن", prevodImenaSure: "Džini", tipSure: "mekanska", brojAjeta: 28),
    Sura(redniBroj: 73, sura: "El-Muzzemmil", imeSureNaArapskom: "المزمل", prevodImenaSure: "Umotani", tipSure: "mekanska", brojAjeta: 20),
    Sura(redniBroj: 74, sura: "El-Mudessir", imeSureNaArapskom: "المدثر", prevodImenaSure: "Ogrnuti", tipSure: "mekanska", brojAjeta: 56),
    Sura(redniBroj: 75, sura: "El-Kijame", imeSureNaArapskom: "القيامة", prevodImenaSure: "Smak svijeta", tipSure: "mekanska", brojAjeta: 40),
    Sura(redniBroj: 76, sura: "El-Insan", imeSureNaArapskom: "الإنسان", prevodImenaSure: "Čovjek", tipSure: "medinska", brojAjeta: 31),
    Sura(redniBroj: 77, sura: "El-Murselat", imeSureNaArapskom: "المرسلات", prevodImenaSure: "Onaj koji šalje", tipSure: "mekanska", brojAjeta: 50),
    Sura(redniBroj: 78, sura: "En-Nebe'", imeSureNaArapskom: "النبأ", prevodImenaSure: "Vijest", tipSure: "mekanska", brojAjeta: 40),
    Sura(redniBroj: 79, sura: "En-Nazi'at", imeSureNaArapskom: "النازعات", prevodImenaSure: "Oni koji čupaju", tipSure: "mekanska", brojAjeta: 46),
    Sura(redniBroj: 80, sura: "Abese", imeSureNaArapskom: "عبس", prevodImenaSure: "Mrštiti se", tipSure: "mekanska", brojAjeta: 42),
    Sura(redniBroj: 81, sura: "Et-Tekvir", imeSureNaArapskom: "التكوير", prevodImenaSure: "Gasenje", tipSure: "mekanska", brojAjeta: 29),
    Sura(redniBroj: 82, sura: "El-Infitar", imeSureNaArapskom: "الإنفطار", prevodImenaSure: "Puknuće", tipSure: "mekanska", brojAjeta: 19),
    Sura(redniBroj: 83, sura: "El-Mutaffifin", imeSureNaArapskom: "المطففين", prevodImenaSure: "Varalice", tipSure: "mekanska", brojAjeta: 36),
    Sura(redniBroj: 84, sura: "El-Inšikak", imeSureNaArapskom: "الإنشقاق", prevodImenaSure: "Cijepanje", tipSure: "mekanska", brojAjeta: 25),
    Sura(redniBroj: 85, sura: "El-Burudž", imeSureNaArapskom: "البروج", prevodImenaSure: "Zviježđa", tipSure: "mekanska", brojAjeta: 22),
    Sura(redniBroj: 86, sura: "Et-Tarik", imeSureNaArapskom: "الطارق", prevodImenaSure: "Noćni putnik", tipSure: "mekanska", brojAjeta: 17),
    Sura(redniBroj: 87, sura: "El-A'la", imeSureNaArapskom: "الأعلى", prevodImenaSure: "Uzvišeni", tipSure: "mekanska", brojAjeta: 19),
    Sura(redniBroj: 88, sura: "El-Gašije", imeSureNaArapskom: "الغاشية", prevodImenaSure: "Nevolja", tipSure: "mekanska", brojAjeta: 26),
    Sura(redniBroj: 89, sura: "El-Fedžr", imeSureNaArapskom: "الفجر", prevodImenaSure: "Zora", tipSure: "mekanska", brojAjeta: 30),
    Sura(redniBroj: 90, sura: "El-Beled", imeSureNaArapskom: "البلد", prevodImenaSure: "Grad", tipSure: "mekanska", brojAjeta: 20),
    Sura(redniBroj: 91, sura: "Eš-Šems", imeSureNaArapskom: "الشمس", prevodImenaSure: "Sunce", tipSure: "mekanska", brojAjeta: 15),
    Sura(redniBroj: 92, sura: "El-Lejl", imeSureNaArapskom: "الليل", prevodImenaSure: "Noć", tipSure: "mekanska", brojAjeta: 21),
    Sura(redniBroj: 93, sura: "Ed-Duha", imeSureNaArapskom: "الضحى", prevodImenaSure: "Jutro", tipSure: "mekanska", brojAjeta: 11),
    Sura(redniBroj: 94, sura: "El-Inširah", imeSureNaArapskom: "الشرح", prevodImenaSure: "Širenje", tipSure: "mekanska", brojAjeta: 8),
    Sura(redniBroj: 95, sura: "Et-Tin", imeSureNaArapskom: "التين", prevodImenaSure: "Smokva", tipSure: "mekanska", brojAjeta: 8),
    Sura(redniBroj: 96, sura: "El-Alek", imeSureNaArapskom: "العلق", prevodImenaSure: "Ugrušak", tipSure: "mekanska", brojAjeta: 19),
    Sura(redniBroj: 97, sura: "El-Kadr", imeSureNaArapskom: "القدر", prevodImenaSure: "Noć sudbine", tipSure: "mekanska", brojAjeta: 5),
    Sura(redniBroj: 98, sura: "El-Bejjine", imeSureNaArapskom: "البينة", prevodImenaSure: "Dokaz", tipSure: "medinska", brojAjeta: 8),
    Sura(redniBroj: 99, sura: "Ez-Zelzele", imeSureNaArapskom: "الزلزلة", prevodImenaSure: "Potres", tipSure: "medinska", brojAjeta: 8),
    Sura(redniBroj: 100, sura: "El-Adijat", imeSureNaArapskom: "العاديات", prevodImenaSure: "Trkači", tipSure: "mekanska", brojAjeta: 11),
    Sura(redniBroj: 101, sura: "El-Kari'a", imeSureNaArapskom: "القارعة", prevodImenaSure: "Udar", tipSure: "mekanska", brojAjeta: 11),
    Sura(redniBroj: 102, sura: "Et-Tekasur", imeSureNaArapskom: "التكاثر", prevodImenaSure: "Gomilanje", tipSure: "mekanska", brojAjeta: 8),
    Sura(redniBroj: 103, sura: "El-Asr", imeSureNaArapskom: "العصر", prevodImenaSure: "Vrijeme", tipSure: "mekanska", brojAjeta: 3),
    Sura(redniBroj: 104, sura: "El-Humeze", imeSureNaArapskom: "الهمزة", prevodImenaSure: "Opadač", tipSure: "mekanska", brojAjeta: 9),
    Sura(redniBroj: 105, sura: "El-Fil", imeSureNaArapskom: "الفيل", prevodImenaSure: "Slon", tipSure: "mekanska", brojAjeta: 5),
    Sura(redniBroj: 106, sura: "Kurejš", imeSureNaArapskom: "قريش", prevodImenaSure: "Kurejšije", tipSure: "mekanska", brojAjeta: 4),
    Sura(redniBroj: 107, sura: "El-Ma'un", imeSureNaArapskom: "الماعون", prevodImenaSure: "Sitnice", tipSure: "mekanska", brojAjeta: 7),
    Sura(redniBroj: 108, sura: "El-Kevser", imeSureNaArapskom: "الكوثر", prevodImenaSure: "Obilje", tipSure: "mekanska", brojAjeta: 3),
    Sura(redniBroj: 109, sura: "El-Kafirun", imeSureNaArapskom: "الكافرون", prevodImenaSure: "Nevjernici", tipSure: "mekanska", brojAjeta: 6),
    Sura(redniBroj: 110, sura: "En-Nasr", imeSureNaArapskom: "النصر", prevodImenaSure: "Pomoć", tipSure: "medinska", brojAjeta: 3),
    Sura(redniBroj: 111, sura: "El-Mesed", imeSureNaArapskom: "المسد", prevodImenaSure: "Konopac", tipSure: "mekanska", brojAjeta: 5),
    Sura(redniBroj: 112, sura: "El-Ihlas", imeSureNaArapskom: "الإخلاص", prevodImenaSure: "Iskrenost", tipSure: "mekanska", brojAjeta: 4),
    Sura(redniBroj: 113, sura: "El-Felak", imeSureNaArapskom: "الفلق", prevodImenaSure: "Zora", tipSure: "mekanska", brojAjeta: 5),
    Sura(redniBroj: 114, sura: "En-Nas", imeSureNaArapskom: "الناس", prevodImenaSure: "Ljudi", tipSure: "mekanska", brojAjeta: 6)
]

 
